version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9092:9092"
    networks:
      - kafka-net
    volumes:
      - D:/docker-data/kafka-data:/kafka/kafka-logs  # Adjust path
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:1"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 #,PLAINTEXT_INTERNAL://0.0.0.0:29092   #Where Kafka binds inside the container
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092 #,PLAINTEXT_INTERNAL://kafka:29092  #The address clients will use to connect
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9093:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - kafka-net
networks:
  kafka-net: