spring:
  application:
    name: pki-service
  datasource:
    url: jdbc:mysql://localhost:3306/pki_ca?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: danial
    password: nopass
    driver-class-name: com.mysql.cj.jdbc.Driver
    #initialization-mode: always
    #platform: mysql  # optional, helpful for Spring Boot to locate `schema-mysql.sql` if used
  sql:
    init:
      mode: always            # ✅ Force schema.sql to run
      continue-on-error: true # ✅ Optional, won't fail on minor SQL errors

  jpa:
    generate-ddl: false
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
#      resourceserver:
#        jwt:
#          public-key-location: classpath:public-key.pem
##          jwk-set-uri: http://localhost:9003/oauth/token_key
#      resource:
#        jwt:
#          key-store: classpath:jwt-keystore.p12
#          key-store-password: Da123!@#
#          key-alias: jwt-key
#          key-store-type: PKCS12
server:
  port: 9005
#  ssl:
#    enabled: true
#    key-store: classpath:mTLS/customerService-keystore.p12
#    key-store-password: "Da123!@#"
#    key-alias: customerService
#    key-store-type: PKCS12
#    trust-store: classpath:mTLS/customerService-truststore.p12
#    trust-store-password: "Da123!@#"
#    trust-store-type: PKCS12
#    client-auth: need
#eureka:
#  client:
#    service-url:
#      defaultZone: https://localhost:8761/eureka
#    registerWithEureka: false
#    fetchRegistry: false
#    enable-ssl: false

eureka:
  client:
    enabled: false

pki:
  certificate:
    validity:
      root: 3650          # 10 years
      intermediate: 1825  # 5 years
      leaf: 365           # 1 year
    password-length: 12
  default-san:
    - "example.local"
    - "api.example.local"
    - "localhost"
    - "127.0.0.1"
  subject:
    common-name: "intermediate-ca"
    organization: "Dotlines"
    organizational-unit: "PKI-Infra"
    country: "US"
    state: "Dhaka"
    locality: "Dhaka"
    email-address: "pki-admin@dotlines.com"
    domain-component: "dotlines"
    serial-number: "DL-CA-001"
    given-name: "Danial"
    surname: "Chakma"
    title: "Security Engineer"
    initials: "DC"
    uid: "pki-service"

app:
  security:
    enabled: false   # or true

ca:
  defaults:
    root:
      keyAlg: "RSA"
      keySize: 4096
      curveName: "" #RSA → curveName is ignored
      signAlg: "SHA256withRSA"
    intermediate:
      keyAlg: "EC"
      keySize: ""
      curveName: "secp384r1" #EC → requires curveName (e.g. secp256r1), keySize is ignored
      signAlg: "SHA384withECDSA"
    leaf:
      keyAlg: "Ed25519" #Ed25519 → no keySize or curveName needed
      keySize: ""
      curveName: ""
      signAlg: "Ed25519"
